# Generated by Django 6.0 on 2025-12-10 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_handicap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tee_name', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('course_tee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf_handicap.course')),
            ],
        ),
    ]
