# Generated by Django 6.0 on 2025-12-10 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf_handicap', '0002_coursetees'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseTees',
            new_name='CourseTee',
        ),
    ]
