# Generated by Django 6.0 on 2025-12-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_handicap', '0003_rename_coursetees_coursetee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursetee',
            old_name='course_tee',
            new_name='course',
        ),
        migrations.AddField(
            model_name='coursetee',
            name='course_par',
            field=models.IntegerField(default=72),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursetee',
            name='course_rating',
            field=models.DecimalField(decimal_places=1, default=99, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursetee',
            name='slope_rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
