# Generated by Django 6.0 on 2025-12-11 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_handicap', '0004_rename_course_tee_coursetee_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(max_length=4)),
                ('date_played', models.DateTimeField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('tee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf_handicap.coursetee')),
            ],
        ),
    ]
