# Generated by Django 6.0 on 2025-12-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_handicap', '0005_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='date_played',
            field=models.DateField(),
        ),
    ]
