# Generated by Django 6.0 on 2025-12-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_handicap', '0006_alter_score_date_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(),
        ),
    ]
